### PR TITLE
Partially fix buffs and techniques that don't work

### PR DESCRIPTION
**Pull request by waveyl**
In this PR, I just fix Half-phantom (half) training. And for some techniques, you may need to use `"crit_ok": true` to limit it only active on a crit. @RedMisao 

Before change: No EFFECT
image

After change:
image
image

### CODE REVIEW

**Comment by RedMisao** [comment]
Nice. I realized some stuff from martial arts and techniques wasn't working, but couldn't figure out how to fix it. I think Tenko has the same problems too, as she also uses weapon-based attacks.

**Comment by waveyl** [comment]
@RedMisao Do you have any plan to update this mod? Looking foward to it.

**Comment by RedMisao** [comment]
Yes, I do. First I have to fix all the errors introduced by changes in base cdda after the last stable update (like those from eoc syntax), then I will continue fixing and adding stuff to the characters.

**Comment by miu135** [comment]
@RedMisao 
I'm sorry to use this to ask but is there any way to contact you?

**Comment by RedMisao** [comment]
> @RedMisao I'm sorry to use this to ask but is there any way to contact you?

I'm in the official cdda discord, you can search my name and DM me through there

**Pull request merged**
